[package]
name = "example_rust_silentpayments"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
bdk_testenv = { version = "0.11.1", path = "../../crates/testenv" }
silentpayments = { version = "0.4.0", path = "../../../rust-silentpayments" }

[lints]
workspace = true
